# https://taskfile.dev

version: "3"

dotenv: [".env", ".env.local"]

includes:
  client: "./client/Taskfile.yml"
  server: "./server/Taskfile.yml"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  up:
    desc: "Start the application containers"
    cmds:
      - docker compose up -d --watch
    silent: true

  stop:
    desc: "Stop the application containers"
    cmds:
      - docker compose down
    silent: true
