name: Client CI

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/client-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/client-ci.yml"
  release:
    types: [published]

defaults:
  run:
    working-directory: ./client

env:
  DOCKER_IMAGE_NAME: astro5-strapi5-example/client

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'release' &&  startsWith(github.event.release.tag_name, 'client-')) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${env.DOCKER_IMAGE_NAME}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            STRAPI_URL=${{ secrets.STRAPI_URL }}
