name: Deploy

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Application to deploy"
        required: true
        default: "server"
      tag:
        description: "Tag to deploy"
        required: true
        default: "latest"
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "Deployment"
