name: Server CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"
  release:
    types: [published]

env:
  DOCKER_IMAGE_NAME: astro5-strapi5-example/server
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'release' &&  startsWith(github.event.release.tag_name, 'server-')) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${env.DOCKER_IMAGE_NAME}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'release' &&  startsWith(github.event.release.tag_name, 'server-') }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          path-to-changelog: server/CHANGELOG.md

      - name: Commit updated CHANGELOG and README files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "chore(release): [skip-ci] ${{ github.event.release.tag_name }}"
          file_pattern: server/CHANGELOG.md

  trigger-deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    needs: release
    if: ${{ github.event_name == 'release' &&  startsWith(github.event.release.tag_name, 'server-') }}
    steps:
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: deploy
          client-payload: '{"app": "server", "tag": "${{ github.event.release.tag_name }}"}'
